# docker-compose.yml
version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gym_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=gym_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"

  worker:
    build: .
    command: celery -A app.workers.tasks worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gym_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./app:/app

  beat:
    build: .
    command: celery -A app.workers.tasks beat --loglevel=info
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gym_db
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=pyamqp://guest@rabbitmq//
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ./app:/app

volumes:
  postgres_data: